---
# tasks file for ipv6
- name: Copy file to server
  copy:
    src: /etc/ansible/roles/ipv6/files/sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
    
- name: Test config
  shell: modprobe ip_conntrack    

- name: Disable IPv6 execute
  shell: sysctl -p 
  register: return_from_shell
  changed_when: no

- name: Show result
  debug:
    msg: "{{ return_from_shell.stdout_lines }}"
 
