---
- name: chrony
  yum: name=chrony state=present

- name: start chrony
  service: name=chronyd state=restarted

- name: Copy file config
  copy:
    src: /etc/ansible/roles/chrony/files/chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Check chronyc sources
  shell: chronyc sources
  register: return_from_shell
  changed_when: no

- name: show previous shell stdout
  debug:
    msg: "{{ return_from_shell.stdout_lines }}"
